name: 'Kubernetes digest updater'
description: 'Greet someone and record the time'
inputs:
  comment: # id of input
    description: 'Lines with this comment will be updated'
    required: false
    default: '$update-digest$'
  prefix: # id of input
    description: 'Prefix to put onto the beginning of image references'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/blueberrymuffin3/kube-digest-updater@sha256:92746e5b0e5d1502ede792c0bd285266324eeb0f19365d3f9d1a842df3ab35e3' # $update-digest$
  args:
  - -comment=${{ inputs.comment }}
  - -prefix=${{ inputs.prefix }}
  - -directory=.
