name: 'Kubernetes digest updater'
description: 'Greet someone and record the time'
inputs:
  comment: # id of input
    description: 'Lines with this comment will be updated'
    required: false
    default: '$update-digest$'
  prefix: # id of input
    description: 'Prefix to put onto the beginning of image references'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/bmxguy100/kube-digest-updater@sha256:07d828e448c04f0733d0142e4a240169d35b71881c3a6020b9b45fefd2abd000' # $update-digest$
  args:
  - -comment=${{ inputs.comment }}
  - -prefix=${{ inputs.prefix }}
  - -directory=.
